### ISSUE TITLE
Encoding of the keys on the nrf9160

### ISSUE THREAD

**Issue by charlesfayal** [NordicPlayground/aws-iot-core-fleet-provisioning-with-nrf9160#11]
Our devices are receiving the keys and storing them but they're not connecting. It appears to be a decoding issue since if we replace the \n symboles with a return on our computers with the certificates manager the same keys work. Right now we're taking the string from the mqtt message and storing it, should we be decoding it somehow before saving it?

**Comment by coderbyheart** [comment]
Hei,

since you've confirmed that the certificates work when programmed using the certificates manager, this is a problem with the firmware, and not a problem with this project.

Please create a [{DevZone](https://devzone.nordicsemi.com/) case instead.

Thank you.

**Comment by coderbyheart** [comment]
Here is a sample: https://github.com/simensrostad/fw-nrfconnect-nrf/commit/1f698ad2f2ddd92854ee0086d7b856fc965acdf5
