### ISSUE TITLE
Unable to bootstrap on Windows 11 (WSL)

### ISSUE THREAD

**Issue by Wickramanayaka** [NordicPlayground/aws-iot-core-fleet-provisioning-with-nrf9160#12]
I am getting below error. Any help to resolve this.

```
root@DESKTOP-D7P7IKQ:/mnt/d/Netanel-UK/aws/aws-iot-core-fleet-provisioning-with-nrf9160# npx cdk bootstrap
/mnt/d/Netanel-UK/aws/aws-iot-core-fleet-provisioning-with-nrf9160/node_modules/@smithy/config-resolver/dist-cjs/index.js:117
    throw new Error("Region is missing");
          ^

Error: Region is missing
    at default (/mnt/d/Netanel-UK/aws/aws-iot-core-fleet-provisioning-with-nrf9160/node_modules/@smithy/config-resolver/dist-cjs/index.js:117:11)
    at /mnt/d/Netanel-UK/aws/aws-iot-core-fleet-provisioning-with-nrf9160/node_modules/@smithy/node-config-provider/dist-cjs/index.js:72:104
    at /mnt/d/Netanel-UK/aws/aws-iot-core-fleet-provisioning-with-nrf9160/node_modules/@smithy/property-provider/dist-cjs/index.js:79:33
    at async coalesceProvider (/mnt/d/Netanel-UK/aws/aws-iot-core-fleet-provisioning-with-nrf9160/node_modules/@smithy/property-provider/dist-cjs/index.js:106:18)
    at async /mnt/d/Netanel-UK/aws/aws-iot-core-fleet-provisioning-with-nrf9160/node_modules/@smithy/property-provider/dist-cjs/index.js:117:20
    at async region (/mnt/d/Netanel-UK/aws/aws-iot-core-fleet-provisioning-with-nrf9160/node_modules/@smithy/config-resolver/dist-cjs/index.js:142:30)
    at async Object.defaultIoTHttpAuthSchemeParametersProvider [as httpAuthSchemeParametersProvider] (/mnt/d/Netanel-UK/aws/aws-iot-core-fleet-provisioning-with-nrf9160/node_modules/@aws-sdk/client-iot/dist-cjs/auth/httpAuthSchemeProvider.js:9:18)
    at async /mnt/d/Netanel-UK/aws/aws-iot-core-fleet-provisioning-with-nrf9160/node_modules/@smithy/core/dist-cjs/index.js:61:5
    at async /mnt/d/Netanel-UK/aws/aws-iot-core-fleet-provisioning-with-nrf9160/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:33:22
    at async file:///mnt/d/Netanel-UK/aws/aws-iot-core-fleet-provisioning-with-nrf9160/cdk/backend.ts:1:262

Node.js v20.12.2

Subprocess exited with error 1
```

**Comment by coderbyheart** [comment]
I looks like you didn't [set up your AWS credentials](https://github.com/NordicPlayground/aws-iot-core-fleet-provisioning-with-nrf9160?tab=readme-ov-file#step-1-provide-aws-credentials).

**Comment by Wickramanayaka** [comment]
I added the credentials into the .envrc file
![aws](https://github.com/NordicPlayground/aws-iot-core-fleet-provisioning-with-nrf9160/assets/16484588/beb21e0b-da08-4c96-ba07-0f329a135a1a)

**Comment by coderbyheart** [comment]
Did you follow the next step?
> If opting for .envrc, ensure prior installation of the [direnv](https://direnv.net/) tool.

**Comment by Wickramanayaka** [comment]
I followed all the steps up to 3 without any issue but Step 3 and 4 are giving me the above error.
![aws2](https://github.com/NordicPlayground/aws-iot-core-fleet-provisioning-with-nrf9160/assets/16484588/5a49aaca-f1ed-4373-8186-a70e56f55157)

**Comment by coderbyheart** [comment]
Did you run `direnv allow`?

**Comment by Wickramanayaka** [comment]
I ran the `direnv allow` command but still getting the same error.

**Comment by coderbyheart** [comment]
Please confirm that

```bash
echo $AWS_REGION
```

prints `us-east-2`.

Otherwise there is a problem with your setup and your environment variables have not been correctly set from you `.envrc` in that case you can always manually set your environment variables in the current shell, by pasting the contents from your `.envrc` into your shell.

**Comment by Wickramanayaka** [comment]
Thank you so much for your kind support. The problem is the environment variables have not been setup correctly. According to your instructions, I set the environment variables manually and everything is working fine now. Thank you again.

**Comment by Wickramanayaka** [comment]
Hi @coderbyheart, could you please let me know where I can find the device side implementation of the fleet provisioning? I have nRF7002DK and nRF9160DK.

**Comment by coderbyheart** [comment]
Here is an example: https://github.com/simensrostad/fw-nrfconnect-nrf/commit/1f698ad2f2ddd92854ee0086d7b856fc965acdf5

**Comment by Wickramanayaka** [comment]
Thank you so much @coderbyheart

**Comment by AbuBakar-WEB1840** [comment]
@Wickramanayaka  did it work for you? 
As i am also working on fleet provisioning using nrf9160. Due to limitation of nrf9160 modem socket size, device is getting reset while receiving the aws response (certificates, and ownership token). Lambda function also do not work with aws reserved topics
